### ISSUE TITLE
Options crash

### ISSUE THREAD

**Issue by shuvashish76** [seht/volumenotification#38]
App crashers when tap on Media / Ring / Call Volume from the application.

### Crash logs:

```
FATAL EXCEPTION: main
Process: net.hyx.app.volumenotification, PID: 17705
android.content.res.Resources$NotFoundException: Drawable net.hyx.app.volumenotification:drawable/ic_outline_volume_up_24px with resource ID #0x7f0800c1
Caused by: android.content.res.Resources$NotFoundException: File res/Lk.xml from drawable resource ID #0x7f0800c1
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
	at android.content.res.Resources.getDrawable(Resources.java:827)
	at android.content.Context.getDrawable(Context.java:635)
	at androidx.core.content.a$a.b(SourceFile:1)
	at androidx.core.content.a.d(SourceFile:1)
	at androidx.appcompat.widget.z0.k(SourceFile:1)
	at androidx.appcompat.widget.z0.j(SourceFile:1)
	at f.a.b(SourceFile:1)
	at androidx.appcompat.widget.q.i(SourceFile:1)
	at androidx.appcompat.widget.r.setImageResource(Unknown Source:4)
	at r3.a.a(SourceFile:1)
	at r3.a.getView(SourceFile:1)
	at android.widget.Spinner.measureContentWidth(Spinner.java:856)
	at android.widget.Spinner.onMeasure(Spinner.java:606)
	at androidx.appcompat.widget.a0.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(Unknown Source:230)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2725)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.view.InflateException: Class not found x
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:222)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:139)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
	... 65 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "x" on path: DexPathList[[zip file "/data/app/net.hyx.app.volumenotification-Wa4rmkqGCmEbhioprjYEMQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.hyx.app.volumenotification-Wa4rmkqGCmEbhioprjYEMQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:203)
	... 69 more
```

### Device details:

App version: 1.2.3.4yes (12340)
Model: Lenovo Tab4 8 Plus
Android: 9

**Comment by seht** [comment]
Thank you for contributing. This should have been fixed with the latest update. (v1.2.6.1)
